name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm@9.15.1

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: pnpm --filter nft-dapp exec playwright install --with-deps

      - name: Lint code
        run: pnpm --filter nft-dapp lint

      - name: Type check
        run: pnpm --filter nft-dapp type-check

      - name: Run unit & integration tests
        run: pnpm --filter nft-dapp test:run

      - name: Run E2E tests
        run: pnpm --filter nft-dapp playwright:test

      - name: Build application
        run: pnpm --filter nft-dapp build
        env:
          VITE_REOWN_PROJECT_ID: ${{ secrets.VITE_REOWN_PROJECT_ID }}
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          VITE_NFT_CONTRACT_ADDRESS: ${{ secrets.VITE_NFT_CONTRACT_ADDRESS }}
          VITE_ENV: production

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: apps/nft-dapp/dist/
          retention-days: 7 